# Use a Python base image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files into the container
COPY . .

# Expose the port the Flask app runs on
EXPOSE 5000

# Set the environment variable if needed.
# ENV FLASK_APP=app.py

# Command to run the Flask application
CMD ["python", "app.py"]